[package]
name = "reckless"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
game = { path = "../game" }
search = { path = "../search" }
evaluation = { path = "../evaluation" }
