name: Feature request
description: Suggest an idea for this project
labels: ["enhancement"]

body:
  - type: textarea
    attributes:
      label: Feature description
    validations:
      required: true
