[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-cpu=native", "-C", "target-feature=-bmi2"]

[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "target-cpu=native", "-C", "target-feature=-bmi2"]

[target.x86_64-pc-windows-gnu]
rustflags = ["-C", "target-cpu=native", "-C", "target-feature=-bmi2"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-cpu=native", "-C", "target-feature=-bmi2"]
