name: Reckless Releases

on: [push, workflow_dispatch]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    name: Build for Linux (${{ matrix.rust_cpu }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - rust_cpu: x86-64
            sde_flag: -pnr
          - rust_cpu: x86-64-v2
            sde_flag: -bdw
          - rust_cpu: x86-64-v3
            sde_flag: -skx

    env:
      TARGET: ${{ matrix.target }}
      RUST_CPU: ${{ matrix.rust_cpu }}
      SDE_FLAG: ${{ matrix.sde_flag }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: |
          rustup component add llvm-tools
          cargo install cargo-pgo

      - name: Setup Intel SDE
        uses: petarpetrovt/setup-sde@v3.0
        with:
          sdeVersion: "9.58.0"
          environmentVariableName: SDE_PATH

      - name: Instrument build for PGO
        run: |
          cargo pgo instrument
        env:
          RUSTFLAGS: "-C target-cpu=${{ matrix.rust_cpu }}"

      - name: Run PGO profiling benchmarks
        run: |
          SDE="$SDE_PATH/sde64"
          "$SDE" $SDE_FLAG -- cargo pgo run -- bench
        env:
          RUSTFLAGS: "-C target-cpu=${{ matrix.rust_cpu }}"

      - name: Optimize build with PGO
        run: |
          cargo pgo optimize
        env:
          RUSTFLAGS: "-C target-cpu=${{ matrix.rust_cpu }}"

  build-windows:
    name: Build for Windows (${{ matrix.rust_cpu }})
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - rust_cpu: x86-64
            sde_flag: -pnr
          - rust_cpu: x86-64-v2
            sde_flag: -bdw
          - rust_cpu: x86-64-v3
            sde_flag: -skx

    env:
      RUST_CPU: ${{ matrix.rust_cpu }}
      SDE_FLAG: ${{ matrix.sde_flag }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: |
          rustup component add llvm-tools
          cargo install cargo-pgo

      - name: Setup Intel SDE
        uses: petarpetrovt/setup-sde@v3.0
        with:
          sdeVersion: "9.58.0"
          environmentVariableName: SDE_PATH

      - name: Instrument build for PGO
        run: |
          cargo pgo instrument
        env:
          RUSTFLAGS: "-C target-cpu=${{ matrix.rust_cpu }}"

      - name: Run PGO profiling benchmarks
        shell: pwsh
        run: |
          SDE="$(cygpath -u "$SDE_PATH")/sde64.exe"
          "$SDE" $SDE_FLAG -- cargo pgo run -- bench
        env:
          RUSTFLAGS: "-C target-cpu=${{ matrix.rust_cpu }}"

      - name: Optimize build with PGO
        run: |
          cargo pgo optimize
        env:
          RUSTFLAGS: "-C target-cpu=${{ matrix.rust_cpu }}"
