name: Build and Test

on: [push, pull_request, workflow_dispatch]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up NNUE model
      run: |
        url=$(curl -s https://api.github.com/repos/codedeliveryservice/RecklessNetworks/releases/latest | \
              grep -o '"browser_download_url": *"[^"]*"' | head -n 1 | cut -d '"' -f 4)
        wget -O model.nnue "$url"
        echo "EVALFILE=$(pwd)/model.nnue" >> $GITHUB_ENV

    - name: Build
      run: cargo build --verbose --release

    - name: Build with `datagen` feature
      run: cargo build --verbose --release --features datagen

    - name: Run tests
      run: cargo test --verbose --release
